import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import Footer from "@/components/custom/Footer";
import { Toaster } from 'sonner'
import DashboardHeader from "@/components/custom/DashboardHeader";
import ThemeProvider from "@/components/theme-provider"
import { ReactNode } from "react";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Invoicedia",
  description: "Generated by create next app",
};


interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <Toaster richColors position="bottom-right" />
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            {/* <DashboardHeader /> */}
            <main>
              <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
                {children}
              </ThemeProvider>
            </main>
            {/* <Footer /> */}
          </body>
        </html>
    </ClerkProvider>
  );
}
